---

- name: Add Repository Key by ID
  apt_key:
    id: "{{ _zulu_jdk.apt_repo.key_id }}"
    keyserver: "{{ _zulu_jdk.apt_repo.key_server | default('keyserver.ubuntu.com')  }}"
    state: present

- name: Add Repository URL
  apt_repository:
    repo: "{{ _zulu_jdk.apt_repo.repo_line }}"
    state: present

- name: Install Zulu Repo
  apt:
    state: latest
    name: "zulu-repo"

- name: Install Zulu JDK
  apt:
    state: latest
    name: "{{ _zulu_jdk.package_name }}"
    update_cache: yes

- name: "Set security setting for DNS cache ttl"
  lineinfile:
    path: "{{ _zulu_jdk.install_dir }}/{{ 'conf' if _zulu_jdk.package_name == 'zulu-11' else 'jre/lib' }}/security/java.security"
    regexp: '^(.*)networkaddress.cache.ttl=(.*)$'
    line: "networkaddress.cache.ttl={{ _zulu_jdk.security.dns_cache_ttl }}"

- name: "Set security setting for DNS cache negative ttl"
  lineinfile:
    path: "{{ _zulu_jdk.install_dir }}/{{ 'conf' if _zulu_jdk.package_name == 'zulu-11' else 'jre/lib' }}/security/java.security"
    regexp: '^(.*)networkaddress.cache.negative.ttl=(.*)$'
    line: "networkaddress.cache.negative.ttl={{ _zulu_jdk.security.dns_cache_negative_ttl }}"
